### ISSUE TITLE
Newest build is flooded with memory allocation warnings

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#174]
**Describe the bug**
The bug is this:
```
warn:  Requested memory allocation but failed to find space in preferred heaps, this alloc will be demoted to slower memory segments
warn:    Size:      256
warn:    Category:  1
warn:    Alignment: 256
warn:    Mem property flags: 0xb
warn:    Mem allocate flags: 0x2
warn:    Mem types: 0x1f
```
[gameexe]_d3d9.log is flooded with this (and variations of it) on nearly every game I've tried. Changing the shared heap size does not prevent this

Remix CI e010672
Bridge CI 4d6dc56
3070 ti
531.29
Any game (Barnyard, Battlefield 2, Flatout)

**Attach logs!**
[Barnyard 1080p no sky_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11581373/Barnyard.1080p.no.sky_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11581374/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11581375/NvRemixBridge.log)

**To Reproduce**
1. Install the latest CI builds of Remix and the bridge
2. Run a game

**Expected behavior**
This warning spamming logs is fairly new and hasn't occurred on previous builds, even with the same settings

**Comment by anon-apple** [comment]
This was fixed in this commit [here](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/98d50162a00a71ab6de8ef93fc8d6b19676d0fe0) (memory warning removed because it isn't actually useful apparently, and an incorrectly requested device local memory property was fixed as well.

It should be fixed in the next release of Remix, or if you build locally from the main branch now it should also be fixed.
