### ISSUE TITLE
!virus!

### ISSUE THREAD

**Issue by EvilXuevil** [NVIDIAGameWorks/rtx-remix#185]
Trojan horse virus detection in NvRemixBridge.exe file
remix version-0.2.0

**Comment by anon-apple** [comment]
This is likely a false positive if you downloaded Remix from either GitHub or built it yourself.

Remix is known to trigger some antiviruses likely due to some of the strange things it does compared to most applications, we sign the GitHub release binaries which helps antiviruses not freak out as much I think, but CI builds from GitHub are unsigned and may cause more false positives as a result.
