### ISSUE TITLE
Mobile Forces -  why no loaded all textures?

### ISSUE THREAD

**Issue by gedas919** [NVIDIAGameWorks/rtx-remix#206]
![20230618110831_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/135579965/0ccc775f-800e-4797-9721-c8db4c1afcc1)

Maybe someone can help solve this problem?

**Comment by anon-apple** [comment]
It is likely the floor geometry is just not being rendered for some reason. You can check if it's actually being rendered or not by looking at some of the debug views in the developer menu (Rendering Tab -> Debug -> Enable Debug View). If you switch the Debug View to something like Geometry Hash and don't see any colored shapes then it's not being rendered.

As to why it's not being rendered if that is the case it could be any number of reasons such as being some sort of shader-based draw Remix doesn't support or is otherwise being ignored for some reason (e.g. in some ignored texture list). Would need more info to say for sure.

**Comment by gedas919** [comment]
> Tikėtina, kad grindų geometrija dėl tam tikrų priežasčių tiesiog nėra pateikiama. Galite patikrinti, ar jis iš tikrųjų pateikiamas, ar ne, pažvelgę į kai kuriuos derinimo rodinius kūrėjo meniu (Atvaizdavimo skirtukas -> Derinti -> Įgalinti derinimo rodinį). Jei perjungiate derinimo rodinį į kažką panašaus į geometrijos maišą ir nematote jokių spalvotų figūrų, jis negeneruojamas.
> 
> Kalbant apie tai, kodėl jis nepateikiamas, jei taip yra, tai gali būti daugybė priežasčių, tokių kaip tam tikras šešėlių pagrindu sukurtas piešinys, "Remix" nepalaiko arba dėl kokių nors priežasčių yra ignoruojamas (pvz., Kai kuriuose ignoruojamuose tekstūrų sąrašuose). Reikėtų daugiau info pasakyti tikrai.

I tried as you said, all the filters are showing, but the bottom and top are just black

**Comment by nv-ajaus** [comment]
@gedas919 For bring up of RTX Remix with a particular game I would recommend reaching out to the community discord server ( https://discord.gg/rtxremix ).
