### ISSUE TITLE
Did it works with Resident Evil 4?

### ISSUE THREAD

**Issue by FutonGama** [NVIDIAGameWorks/rtx-remix#214]
I have tested and looks like its working only on RE4 Steam version 1.1.0 (the last one), but people only uses 1.0.6 version cause its necessary for all the mods to work, trainers, re4 tweaks, re4 dlls like companion trainer or qingsheng dll, its a mandatory version, can you guys make it compatible? Here the EXE: 
[bio4 1.0.6 EXE.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11966987/bio4.1.0.6.EXE.zip)

Thanks for the attention. This will be amazing for this game.

**Comment by FutonGama** [comment]
[bio4 1.1.0 EXE.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11967111/bio4.1.1.0.EXE.zip)
I also have the 1.1.0 EXE here if need. I'm not sure why don't work on the 1.0.6 version. This is super sad, nothing works without the that version for us, mainly RE4Tweaks which is without it the game has numerous of problems and it does not have support for version 1.1.0 precisely because we all are already defined in version 1.0.6, the new one capcom reduced the size of the EXE by modifying some things and with that it made everything stop working so we chose to keep it in version 1.0.6.

**Comment by Mister-Curious** [comment]
I concur that this is a necessary step to support modding for RE4UHD. The 1.10 version broke countless mods because it changed all addresses of the pointers that mods used to inject into memory. 99% percent of all RE4UHD mods require 1.0.6, so please consider adding support for this version of the binary. I'm 5 years deep into one of the largest modding projects ever, and I would be sad to not be able to explore RTX REMIX because of a lack of support. 

Thanks!

**Comment by nv-ajaus** [comment]
@FutonGama For bring up of RTX Remix with a particular game I would recommend reaching out to the community discord server ( https://discord.gg/rtxremix ).
