### ISSUE TITLE
[Crash] Land of the Dead Bridge crashing

### ISSUE THREAD

**Issue by Danp51543** [NVIDIAGameWorks/rtx-remix#221]
**Describe the bug**
- Game randomly crash (Especially when culling happen)
- remix 0.20 or DXVK 1.9.3
- RTX 3060Ti
- 536.67
- 1.0.0.3 Other

**To Reproduce**
1. Open game 
2. Play for a bit
3. Freeze of the game

P.s Also i have dmp file but i cant post it
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12233285/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12233288/d3d9.log)
[LOTD.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12233290/LOTD.log)

**Comment by nv-ajaus** [comment]
Hi @Danp51543  , it has been a while since this issue was filed and we've had a lot of updates since August. Can you please retest this using the latest release ( https://github.com/NVIDIAGameWorks/rtx-remix/releases ), or even better the latest builds (DXVK Remix: https://github.com/NVIDIAGameWorks/dxvk-remix/actions , Bridge Remix: https://github.com/NVIDIAGameWorks/bridge-remix/actions) ?

**Comment by Danp51543** [comment]
I suppose its working fine now (Even so i didnt test cuz i think ive deleted it) Also i noticed that game was crashing only after enabling enchancements
