### ISSUE TITLE
Entropy zero 2 wont launch

### ISSUE THREAD

**Issue by breakdowngamesYT** [NVIDIAGameWorks/rtx-remix#270]
**Describe the bug**
when attempting to open the game with rtx remix installed it does not open and after removing the files it does open
rtx remix version 3.0 DX9
RTX 3060
GeForce game ready driver 545.84 
Steam

**Attached files**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13111528/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13111530/d3d9.log)

**To Reproduce**
1. Download rtx remix version 3.0
2. Put the files in the Entropy Zero 2 directory
3. Move the d3d9.dll to the bin folder and replace the old one
4. Launch the game via steam

**Expected behavior**
for it to open normally and display the welcome to rtx remix message

**Comment by nv-ajaus** [comment]
Hi @breakdowngamesYT, since Entropy: Zero 2 seems to be a mod for Half Life 2, you would need to install all the contents of the remix-0.3.0-release.zip to the `bin` directory of the game. This is generally true for source engine games and mods.

**Comment by nv-ajaus** [comment]
Thank you for filing this issue. Since there hasn't been an update on this issue in a while, I'm going to go ahead and close it for now. If you have an update please feel free to open a new issue. Additionally, there is a community discord server that may be able to help you RTX-Remix bring up with certain titles. https://discord.gg/rtxremix
