### ISSUE TITLE
Dark Messiah not launch

### ISSUE THREAD

**Issue by gunser12** [NVIDIAGameWorks/rtx-remix#38]
**Describe the bug**
- After running the exe file, the process appears in the task manager and disappears after a few seconds and nothing starts
- Remix 0.1.1
- RTX 2070
- 531.41
- Dark Messiah Of Might and Magic (Other)

**Attach logs!**
- Dump [NvRemixBridge.exe_20230413_091106.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218799/NvRemixBridge.exe_20230413_091106.zip)
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218735/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218738/d3d9.log)
- [mm_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218740/mm_d3d9.log)

**To Reproduce**
1. Install Remix
2. Run mm.exe

**Comment by nv-ajaus** [comment]
Hi @gunser12 , I believe this issue is a duplicate (or technically the new issue is the duplicate) of #237 . I believe you should be able to use the latest bridge-remix and dxvk-remix binaries from https://github.com/NVIDIAGameWorks/dxvk-remix/actions and https://github.com/NVIDIAGameWorks/bridge-remix/actions , and see that the crash issue is resolved. I'm going to close this issue as a duplicate for now, but please feel free to reopen it if still persists.
