### ISSUE TITLE
Using RTX Remix to enable DLSS and Reflex on any game

### ISSUE THREAD

**Issue by rxsta** [NVIDIAGameWorks/rtx-remix#422]
Compatibility in my opinion is Remix's biggest flaw right now. In gpu bound games where it only breaks them it would be nice to disable the pbr textures and ray tracing and use DLSS and Reflex to gain fps in those gpu bounds where remix can't do anything.

**Comment by anon-apple** [comment]
I guess this could be done in theory with how Remix is set up, though I'd question how useful it is as DLSS can only run on RTX cards (20 Series and up) whereas DXVK itself (which Remix is built on) only supports games using DirectX 11 and below (which hasn't been the latest version of DX for nearly 9 years now), so such things should run pretty well already on modern GPUs.

What games are you seeing that this would be useful on?

**Comment by rxsta** [comment]
I'm on a 2080 super so it's not exactly a 4k card but it can do 60fps on dx9 games like l4d2 so when i first found out Remix wasn't compatible with it I saw that DLSS and Reflex in my case could still prove useful in giving me more input responsiveness but currently there is no way to disable ray tracing and the other features so the game becomes a broken eyesore.

**Comment by anon-apple** [comment]
Also another thing I forgot about, DLSS requires data from a game such as depth, normals and motion vectors. While this data does usually exist in most slightly more modern games it is non-trivial for Remix to know where these buffers are as Remix is more designed around replacing the entire renderer rather than adding on to it like something like ReShade would. As such there'd still be compatibility issues as not all games expose these buffers in easy to decipher ways (sometimes in non-trivial packed G-Buffer encodings etc).

Really a DLSS injector would be a better thing for a tool like ReShade to handle as it already has access to much of this data (though it may lack things like camera matrices for motion derivation) and compatibility with many games. Enabling Reflex would be doable for Remix though at least.

**Comment by rxsta** [comment]
I see. Well. If anyone can do it surely the people that made the technology can. One can hope at least.

**Comment by anon-apple** [comment]
Yeah like I said it is possible to do, the compatibility just would not be very good and would require per-game configuration and may just not work with how some games render (which is pretty much the situation Remix is in right now, though it'd at least support D3D11 games and whatnot whereas Remix doesn't).

The concern more is just the large time investment to get such a thing working when it's not really what Remix is intended to do (Remix isn't a DLSS injector but rather a full renderer replacement). That's why Reflex injection would be more viable as unlike DLSS it doesn't need all this information from the game and could be easier to add in this way.

**Comment by mirh** [comment]
I mean.. isn't renderer replacement kinda what any DLSS injector would have to do anyway?
Like, I don't think it's something you can just casually sprinkle with reshade. 

Btw reflex is really a fairly simple thing and it can already be enabled just about everywhere with specialK.

**Comment by NV-WendyGram** [comment]
Thank you for reporting this issue and providing your insights. We appreciate your feedback and suggestions on enhancing RTX Remix. While adding DLSS and Reflex to games is an interesting idea, it falls outside the current design goals of Remix, which focuses on full renderer replacement rather than injecting specific features like DLSS.

Given the complexities and significant effort required for such modifications, we are closing this ticket for now. However, your input is valuable, and we will keep it in mind for future considerations.

Thank you for your understanding and continued support.
