### ISSUE TITLE
SceneManager::calculateSceneRight() assumes right handed coordinate system

### ISSUE THREAD

**Issue by jdswebb** [NVIDIAGameWorks/rtx-remix#432]
**Describe the bug**

As of version 0.4.1, `calculateSceneRight` is implemented as:

```
  Vector3 SceneManager::calculateSceneRight() {
    return cross(getSceneForward(), getSceneUp());
  }
```

This assumes a right hand coordinate system, i.e. with `forward = {0,0,1}` and `up = {0,1,0}` it returns `{-1,0,0}`. The function is currently only used in the terrain baking, and it means that the view matrix for the baking is computed incorrectly for games that use a left handed coordinate system.

A simple fix would be to expose the coordinate system of the game as a config option and change it along of the lines of:

```
  Vector3 SceneManager::calculateSceneRight() {
    return isRHCoordinateSystem ? cross(getSceneForward(), getSceneUp()) : cross(getSceneUp(), getSceneForward());
  }
```

I tested this fix out for 'Star Wars Galaxies' and the result was the terrain baking worked correctly. Perhaps there is a smarter way to infer the coordinate system without needing user input though.

**Comment by Hakry** [comment]
Can we get a +feature or +bug and maybe a +runtime.? 

I can confirm the same as jdswebb, we have discussed this a good bit and I have tested the fix locally as well. I do agree with him that it may be able to be hardcoded to use the proper system instead of using a configuration option.

We also can provide a PR if they are accepted.

![Screenshot 2024-02-28 094003](https://github.com/NVIDIAGameWorks/rtx-remix/assets/261603/ea83cec1-8463-4940-a3d5-d83b596f0d54)

**Comment by NV-DM** [comment]
REMIX-2815 for tracking.

**Comment by nsubtil** [comment]
This came up in one of our internal meetings this week. We have some camera matrix conditioning code that we use for captures which covers this and a number of other issues, but it's not used consistently. We're planning to unify that code so that we don't have to keep fixing these bugs in several places.

@xbei-nv for visibility and to determine if we should consider an interim fix.

**Comment by caiocinel** [comment]
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/60858720/8b63edfb-17a5-4c3e-8f9c-663155b6aa48)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/60858720/7c0e7e69-b2ac-466b-a006-7d33141ddc5c)


I was implementing RTX Remix in Postal 2 (Unreal Engine 2) for 1 week struggling with the terrain texture becoming unrecognizable until I got here, and this partially solved my problem (the textures still change as I move the scene, but still It's better than it was before)

**Comment by xbei-nv** [comment]
@jdswebb Hi James, it's great that you get the fix for this issue. Could you create a PR with your fix so we can merge into our branch here?
Besides the core code you showed above, you also need to add an option for LHS/RHS in rtx_options.h to avoid hard-code every time. You need a precise description for the option, such as "Indicates the world space coordinate system handedness.", you can take zUp option as a reference, and be sure to have '.' at the end of your description. Also, remember to mention it's option for "world space", both view and projection can also have their own handedness, but it's unrelated to this fix.

**Comment by jdswebb** [comment]
> @jdswebb Hi James, it's great that you get the fix for this issue. Could you create a PR with your fix so we can merge into our branch here? Besides the core code you showed above, you also need to add an option for LHS/RHS in rtx_options.h to avoid hard-code every time. You need a precise description for the option, such as "Indicates the world space coordinate system handedness.", you can take zUp option as a reference, and be sure to have '.' at the end of your description. Also, remember to mention it's option for "world space", both view and projection can also have their own handedness, but it's unrelated to this fix.

Hi, yes sure, sounds good - I will create the PR in the next couple of days.

**Comment by xbei-nv** [comment]
> > @jdswebb Hi James, it's great that you get the fix for this issue. Could you create a PR with your fix so we can merge into our branch here? Besides the core code you showed above, you also need to add an option for LHS/RHS in rtx_options.h to avoid hard-code every time. You need a precise description for the option, such as "Indicates the world space coordinate system handedness.", you can take zUp option as a reference, and be sure to have '.' at the end of your description. Also, remember to mention it's option for "world space", both view and projection can also have their own handedness, but it's unrelated to this fix.
> 
> Hi, yes sure, sounds good - I will create the PR in the next couple of days.

Cool thanks
