### ISSUE TITLE
[Feature Request] Save denoiser settings in rtx.conf

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#459]
Some games require custom denoiser settings to fix visual bugs or otherwise improve visual quality. An example: FNV, BeamNG.drive, and Skyrim all benefit from using ReBLUR instead of ReLAX. Saving these settings in rtx.conf would be a great help.

**Comment by nsubtil** [comment]
This was a conscious decision. The denoiser settings depend on intrinsic characteristics of the renderer and are not meant to be tweaked per game. We often have to modify these settings together with changes to the renderer itself, so we consider them part of the denoiser integration, instead of graphical settings that can be tuned by a mod.

That said, the implication here is that the denoisers (+ default settings) should largely work independent of content. If the denoisers are not working correctly on specific games, that sounds like a bug.

Can we get tickets filed for the IQ issues in those titles?

**Comment by Kim2091** [comment]
Currently we have been filing tickets per game, but there hasn't been much progress on them. So I figured a more generalized solution might be better. Your explanation makes sense though.

https://github.com/NVIDIAGameWorks/rtx-remix/issues/277
Here's one example. I believe there were some others in the past, although integrated into other issues.

**Comment by NV-LL** [comment]
Thanks for your feedback @Kim2091! It's always helpful to raise issues like this, even if we ultimately decide to handle them differently. We'll focus on the tickets filed for individual games for now, but please keep sending feedback when you have it.
