### ISSUE TITLE
Poor performance on RDNA 2 (Windows) with Remix 0.4 and newer

### ISSUE THREAD

**Issue by McMasterGold** [NVIDIAGameWorks/rtx-remix#503]
With Remix 0.4 and newer, performance on RDNA 2 GPUs on Windows (might not be representative for Linux) is reduced by approximately 2-3x, which is a very significant impact.

For my tests, I am using Portal with RTX. The DLSS 3.5 patch (from 14th March 2024) which updated the game's Remix runtime to 0.4 clearly exhibited the issue. However, _downgrading to Remix 0.3_ fixes the issue and performance is back to what it used to be. Similarly, _updating the pre-patch version to Remix 0.4_ would also cause the exact same issue.

The problem exists in the newer runtimes as well. I have tried Remix 0.4.1 and 0.5.0, as well as the newest artifacts from dxvk-remix and bridge-remix, and the problem is not resolved. Remix 0.3 is the way to go.

I am using the Radeon RX 6700 with the latest 24.4.1 drivers on Windows 11. The same issue could also be noted with 2023 drivers, so it is likely not dependent on the drivers.

I am uploading the log files from both runtimes. rtx.conf remains the same between the two.
[remix0.3.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/15252406/remix0.3.zip)
[remix0.4.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/15252407/remix0.4.zip)
[rtx.conf.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/15252495/rtx.conf.txt)
![REMIXdiff](https://github.com/NVIDIAGameWorks/rtx-remix/assets/4408387/1fae8400-ab68-43be-8fc7-79baca3e9f2c)

**Comment by anon-apple** [comment]
Note just because a version is newer does not mean performance will be better exactly. In Remix we often add new features for higher fidelity rendering and leveraging capabilities of newer hardware, for instance DLSS-RR for Nvidia Ada GPUs in Remix 0.5. This in turn can often mean that performance will get worse over time for existing hardware if it's using such newer potentially heavier features meant for newer cards, or just because our baseline acceptable performance expectations slowly raise to fit said hardware (more features and higher quality rendering eventually necessitate performance cost).

In short, comparing merely the framerate here without actually looking at the visual differences between these versions isn't exactly a fair comparison, so the number is a bit deceptive.

Of course, there could be some sort of specific performance regression going on here that is avoidable, but it can be difficult to tell exactly what is performing so poorly on AMD to begin with due to how dependent on driver stuff performance it is (e.g. shader code compilation) and the limited public tooling available for performance analysis (RGP isn't quite as detailed as say NSight in analyzing such things unfortunately last I checked).

**Comment by McMasterGold** [comment]
Understood, and it is clear from the screenshot that the path-tracing algorithm is different. But a 2-3x performance decrease is very significant, and I know that recently there have been large improvements for Radeon/Linux and RDNA 3/Windows, so I figured I would add in a report for RDNA 2 in case it is indeed something that could be avoided. I appreciate your efforts!

**Comment by McMasterGold** [comment]
Have older commits of dxvk-remix been saved anywhere? GitHub only saves builds for up to 90 days, and I am getting errors when trying to compile from older commits, only the most recent one does not fail.

**Comment by Kim2091** [comment]
@McMasterGold I have multiple older builds of Remix. Post what you need and I can send it to you

**Comment by McMasterGold** [comment]
@Kim2091 Thank you! If it's not too much trouble, anything you have from October-December 2023 (between Remix 0.3 and 0.4) would help! Otherwise, a build from mid-November would at least halve the amount of commits that need to be investigated.
