### ISSUE TITLE
[Toolkit feature]: Option to save Captures folder into Project directory folder

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#546]
### What is the context of the feature/improvement?

When creating the project, I think it'd be nice to have the option to save the captures taken in the rtx-remix folder, and create a symlink from captures to the main Project folder captures folder. 

### Please describe the feature/improvement?

This feature would allow for the captures to be saved and housed in  the project directory folder, allowing for the captures folder in rtx-remix to be cleared, without losing the captures as now they're also saved in  the "captures" folder inside of the project directory. This would be helpful on games that can be used multiple times with Remix, like Garrysmod. I can start on a map in Garrysmod, start up a new Project and load in the captures, but when I go to start a different map and clear the captures folder in the rtx-remix folder, I lose those captures. Then when I go back to finish the project, my captures are now gone. I think a more finite solution would be for the options for the captures to be copied and then housed a captures folder inside the project directory. Additionally, a possible symlink to be made so that any additional captures that happen can be moved/copied to the new captures inside of the project directory. 

### What would be your solution? (optional)

I would have this option be made selectable at the beginning of the project, and possibly anytime after the projects made. I think this would help a lot of modders out, and it'd be nice to house the entire project and all of its materials inside 1 folder.

### Version

2024.3.1

**Comment by po-trottier** [comment]
Hey! I think I'm misunderstanding your issue because what the app currently does is basically exactly what you described:
- Capture -> saved in` rtx-remix/captures/*`
- Create a Project -> Find the `rtx-remix` directory -> symlink `rtx-remix` directory in the project directory (as `deps`)
- From there the project is setup so that your list of captures is live-linked to your `rtx-remix` directory in your game, but the project sublayer path points to `./deps/captures`

**Comment by skurtyyskirts** [comment]
Hello!

Ahh yes, the .deps folder would point to the captures folder to reference the captures when creating the project. But, this only points to the captures that are currently in the rtx-remix captures folder. If a separate mod was to be created using the same game, the captures folder would need to be wiped and the previous captures would be lost - therefore deleting the captures the .dep folder was pointing to, leaving a project without captures if the modder forgets to backup their captures.

This would be a feature to "save captures at the time of project creation", copying the captures folder into the project directory so that the captures used to create the mod are saved at the present time, without relying on the dep folder to point to captures in the rtx-remix folder.

This request would be useful for mods that use the same game often, like Gmod for example.

**Comment by po-trottier** [comment]
Is there a reason why you need to delete the existing captures when you change maps? Wouldn't you simply be able to capture your captures with names like `map_01_{timestamp}.usd`, `map_02_{timestamp}.usd`?  That would allow you to have all your captures separated by-map but in the same directory?

**Comment by skurtyyskirts** [comment]
I'm a fan of that idea, I think my main want/desire to want to separate the captures folder into a project folder is to keep the textures separate when upscaling. When I capture a certain map/scene, they'd all go into the textures folder, and from there I'd have to separate and sort through which textures are only the ones I'm needing for that mod, rather than grabbing all of them each time I run an upscale. 

Everything could be housed in the rtx-remix directory, but storage would quickly become an issue. For my Gmod rtx mods, keeping a clean captures folder was nice when upscaling and pointing the upscaler to my textures folder without having to worry about other textures from a separate mod unrelated going into the mix. And once this mod was finished, I could upload to ModDB and delete the captures folder and save up storage for the next mod.

My workflow now is to save all of my mod projects on a hard drive (storage isn't an issue for me, but it could be for others) sorted by game. Everything is housed into these project folders, including the captures (the deps folder becomes empty upon clearing the captures folder).

This allows me to put a mod project down, while continuing with another one, without housing everything in the rtx-remix folder, or clearing out the captures without worry about removing captures for other projects. 

![Screenshot 2024-07-23 153006](https://github.com/user-attachments/assets/d8f34a6a-758f-49cb-9605-f0cbd6a69b6d)

**Comment by po-trottier** [comment]
If this is workflow-specific I'm thinking the upcoming REST API might solve your issue (add the ability to fetch all the textures in your project using the API). That might fix the need to separate the textures per-mod, as you'll be able to simply send 1 request and get a list of all the textures in your project, and change the loaded captures as desired.

The only reason I'm hesitant to add a "Copy Captures to Project" feature is that I can definitely see that as being a potential confusion point for users. Say a user checks the box, then they take a new capture and it doesn't show up in the capture list because they are copied and not symlinked. 

Conversely, if a user deletes their captures from `rtx-remix/mods` and they still have mods in their project they might be confused.

For non-technical users, the difference between symlinks and directories is not always clear and mixing the 2 can lead to lots of confusion (as seen with the `deps` symlink in the project directory) so I would like to try to keep the hierarchy as simple as possible for the average user to be comfortable with project structures (it's already a bit confusing with the infinitely recursing symlinks). 

Do you think the REST API would be able to solve your upscaling workflow needs? If not what would be the behavior that would on the toolkit side?

**Comment by skurtyyskirts** [comment]
Ahhh, that would be perfect! That would remedy my need to keep captures separate indeed. I see how this request would inherently cause possible hiccups for users down the line. I'll go ahead and close this request, and look forward to trying the REST API! :) Thanks for you help!
