### ISSUE TITLE
[Runtime Bug]: Massive performance regressions since 0.3.0

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#572]
### Describe the bug

There are measurable performance regressions from build 0.3.0 all the way up to the very latest GitHub Actions builds. This applies to all games.

I performed benchmarks after a user brought up performance regressions in our Discord server:
0.3.0 = 95 FPS
0.4.1 = 86 FPS
0.5.1 = 82 FPS
Latest action builds (bridge 85 and dxvk 603) = 65 FPS

### How do you reproduce the bug?

I tested in The Simpsons Hit and Run. 

Use this rtx.conf file: 
[rtx.zip](https://github.com/user-attachments/files/16481048/rtx.zip)

I loaded the game with these settings in Lucas' Launcher:
![image](https://github.com/user-attachments/assets/78c7324b-952b-4d57-800c-2323d1d1e620)

Simply load the game and do not move the camera. Measure FPS after 1 minute

### What is the expected behavior?

Performance should not have regressed this massively

### Version

All

### Media

Look here for screenshots: https://discord.com/channels/1028444667789967381/1228440201139851295/1269307220361740359

**Comment by NV-LL** [comment]
REMIX-3422 for tracking

**Comment by AlexDunn** [comment]
Small update here.  Coincidently, we have been looking at GPU performance around the time this issue was filed.  As such we have a number of performance improvements submitted over the last couple weeks.  Below is a complete list of all the optimizations to date.

With all of these performance should be better than 0.3 in some cases (particularly in decal/particle heavy scenes).  In other cases (more general cases) there is still some work to do.  Please, if you get a sec, try the latest action build on github and let us know.

https://github.com/NVIDIAGameWorks/dxvk-remix/commit/1cec750e77b78b899ce8616cf5fe0742ef766020
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/0d423f8df79c07d0c486afd4da1ada92b17bea62
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/b698be7001a21ed2ba2e4fb842ce84ae79939105
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/f4e44193be8de63e048c8ca8c2ace0e1609ffc64
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/33e8c58cda95107772e4a1eb86bc80c1712c6a22
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/5b3957bad1de4fa5b3935c2d5f639266d39a29b8
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/eaed7a2dbf899f52fd7a7e39f06f51b67b439b2f
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/553a6ecc0948ea6298157e9d3acf29371db78710
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/bae3c2ce6fcd6938e6ccb09de0d1cdfe54161419
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/c9b44c3d7fc857210abad96f0a76da96ce877078
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/c9b44c3d7fc857210abad96f0a76da96ce877078
https://github.com/NVIDIAGameWorks/dxvk-remix/commit/277c3f35ec7383ea1b270ddd5e1030879d3174b7

**Comment by McMasterGold** [comment]
The latest submodules fix the issue I noted in #503 and performance is indeed better than Remix 0.3. Thank you!

![remix-main+1758e0fd](https://github.com/user-attachments/assets/1130e2fe-3051-4450-8a5a-72a5cab9291a)

**Comment by Kim2091** [comment]
Awesome! I did a test about 5 days ago and it was getting closer and closer to 0.3.0 on Nvidia GPUs. You can read my testing here: https://discord.com/channels/1028444667789967381/1028444668918235197/1275210861241303182

I'll test again next week when I have some time. Thank you guys 🙂

**Comment by AlexDunn** [comment]
Thank you.  @McMasterGold seems we should close #503 based on this comment.

@Kim2091 thanks, I see your testing may be missing two cruicial optimizations.  I expect a 5~10% speedup on your previous test

**Comment by Kim2091** [comment]
Okay, so I just tested the latest builds as of this post, and sadly performance isn't quite at 0.3.0's level in this specific test.

It's about on par with 0.5.1. 0.3.0 still has a lead of about 13 FPS.

However it's extremely impressive how quickly performance was restored to 0.5.1's level 😃

**Comment by NV-LL** [comment]
Hi @Kim2091 - as you've noticed, we've been hard at work making headway with runtime performance. We've tackled a lot of the low-hanging fruit to bring it in line with prior runtime versions. We'll continue to make more improvements (some by detecting additional low-hanging fruit, and some by pursuing new techniques).
 
If you identify any parts of the runtime code that may give us a clue of additional avenues to pursue, feel free to share by filing a new ticket. 
 
Otherwise, we'll be closing this ticket and keep working to make the runtime perform better.
