### ISSUE TITLE
[Runtime Bug]: Reference Mode disabled while Ray Reconstruction enabled

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#597]
### Describe the bug

It looks like in the runtime when Ray Reconstruction is enabled, Reference Mode becomes greyed out. But, if I turn off Ray Reconstruction and enable Reference Mode, I'm then able to turn Ray Reconstruction back on. This produces a clearer image as well, the two seem to be able to work together. Sometimes I use reference mode for screenshots as it sometimes makes an even clearer image. 

### How do you reproduce the bug?

1.) Turn on Ray Reconstruction, see Reference mode greyed out.
2.) Turn off Ray Reconstruction, turn  Reference mode on.
3.) Turn Ray Reconstruction back on, see improved image

### What is the expected behavior?

The runtime should...

### Version

Build #634

**Comment by anon-apple** [comment]
This is intended behavior, DLSS Ray Reconstruction is essentially a denoiser, so when it is enabled all other denoiser stuff is disabled (e.g. NRD and whatnot). Reference Mode is a specific option for the NRD denoiser which allows for passing data directly through, so it naturally is disabled when DLSS-RR is in use.

Conceptually you wouldn't want to use reference mode with DLSS-RR enabled in general because reference mode is specifically there to disable denoising, so using it while a denoiser is in use isn't how it's supposed to be used.

That said, there are some cases I am seeing where despite that option being greyed out the Reference Mode option still takes effect. Specifically a median-like firefly filter we have is disabled when Reference Mode is enabled, though that would make the signal more noisy typically so I am not sure if it'd cause the changes you are seeing.

Can you perhaps provide a screenshot of the differences in quality you're seeing when you do this? Thanks.

**Comment by skurtyyskirts** [comment]
Ahh I see. It looks like when I have RR enabled while Reference mode is on, the little dots showing are practically gone now when I'm moving. I took the screenshot after waiting awhile keeping still looking at a scene. Here's some screenshots demonstrating how when RR is on the image clears up in the water.

![RayReconstruct1](https://github.com/user-attachments/assets/34c7ca12-ab5a-49fe-a666-26ce7426c1d5)
![RayReconstruct2](https://github.com/user-attachments/assets/d5a0a35f-d0c2-415d-97e8-8d11afdbc013)
![ReferenceMode1](https://github.com/user-attachments/assets/69a98674-80d0-4753-91fa-e138509698f9)
![ReferenceMode2](https://github.com/user-attachments/assets/bbb27a3a-3f99-4847-b0a1-930da5c945cc)

**Comment by anon-apple** [comment]
Well yeah like I said DLSS-RR is a denoiser, so it's going to denoise the scene, comparing it to reference isn't really showing much and isn't really a valid comparison as it's comparing raw accumulated reference data with denoised data.

The thing that would be a meaningful comparison DLSS-RR+Reference mode on vs DLSS-RR+Reference mode off as that is where the current small bug I noticed would be visible (enabling Reference mode while DLSS-RR is on essentially disables firefly filtering which may cause additional noise).

**Comment by NV-LL** [comment]
Hi @skurtyyskirts - reference mode is meant to be there to accumulate multiple rays over time, and to produce a ground-truth frame against which to compare the accuracy of our real-time path tracer. We don't intend for it to be a screenshot mode, and we'd actually caution against using it as such, as it does not represent a real-time image (and may in some ways underperform as compared to Ray Reconstruction).
 
While we can see this would be useful to have, we'll likely be spending our time on bugs that affect development of mods before we turn to features that support use cases like screenshotting. For what it's worth, we encourage you to file any bugs related to Ray Reconstruction where it falls short of the reference mode - we'd love to spend cycles making our real-time rendering look as good as possible for RTX Remix mods.
