### ISSUE TITLE
[Runtime Feature]: Vulkan beta driver support

### ISSUE THREAD

**Issue by shoober420** [NVIDIAGameWorks/rtx-remix#612]
### What is the context of the feature/improvement?

I use the Vulkan beta driver to get the latest features for Vulkan titles, or anything that utilizes Vulkan. I decided to give RTX Remix a try with Max Payne, but get an error that my driver is too old and needs to update. The game asks for 560.81 stable, but Im using 553.02 Vulkan beta driver. Please allow support for Vulkan beta drivers or allow a way to bypass the driver check.

### Please describe the feature/improvement?

Bypass driver version check to allow Vulkan beta drivers.

### Version

0.5.4

### Media

N/A

**Comment by nsubtil** [comment]
We have an environment variable, DXVK_REMIX_NVIDIA_MIN_DRIVER, that can override the min driver version. Setting DXVK_REMIX_NVIDIA_MIN_DRIVER=553.02 should work for the current VK beta driver.

Can you try that and confirm if it works for you?

(Note that we often bump the min driver version due to incompatibilities between Remix and specific drivers, so we may not be able to look at Remix bugs filed on drivers below our min spec.)

**Comment by shoober420** [comment]
I made two reg files to Enable and Disable RTX Remix Vulkan beta driver support.

https://github.com/shoober420/windows11-scripts/blob/main/EnableRTXRemixVulkanBeta.reg

https://github.com/shoober420/windows11-scripts/blob/main/RemoveRTXRemixVulkanBeta.reg

**Comment by shoober420** [comment]
I just tested this on Max Payne RTX mod, and get an error saying my 4090 doesnt support the required features for RTX Remix.

![20240925_000444 (1).jpg](https://github.com/user-attachments/assets/59dfd5e1-c249-4772-a516-189389ba26cc)

This shouldnt be, considering the Vulkan beta drivers include a newer version of Vulkan and more Vulkan features than stable right?

**Comment by shoober420** [comment]
Here is the mentioned log file from the error.

![eEe3mzrR.txt](https://github.com/user-attachments/files/17126778/eEe3mzrR.txt)

**Comment by nsubtil** [comment]
Thanks for confirming that the environment variable works.

Unfortunately, that driver is below our min spec. We don't recommend running beta drivers in general, they're only meant for developers to provide feedback on upcoming Vulkan API features. The beta drivers largely won't make a difference on shipping titles either, applications also need to be modified in order to add support for any new Vulkan features.

I'd recommend using the regular public drivers to run Remix. If those happen not to work for you, you can always open a new ticket.

**Comment by shoober420** [comment]
Thanks for the information. I thought the Vulkan beta drivers would have more features and newer specs than stable. It appears that Vulkan beta drivers are missing certain specs, but beta testing other features. I was under the impression that the Vulkan beta would have more specs than stable, but it looks like it has older specs but newer features? Very odd mix, but thank you.
