### ISSUE TITLE
[Runtime Feature]: Replace d3d8to9 with dxwrapper

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#629]
### What is the context of the feature/improvement?

DXWrapper has far more features, many of which can improve compatibility of games with Remix.

### Please describe the feature/improvement?

Currently crosire's d3d8to9 wrapper is packaged in with the Remix runtime. However, dxwrapper contains d3d8to9 along with many other functions (including its own dd7to9, a partially functional DX7 to DX9 wrapper) + additional logging.

Other such features include:
- Forcibly disabling AA
- Forcing windowed mode (which prevents crashes in some games)
- some additional API control

### What would be your solution? (optional)

Replace d3d8to9 with dxwrapper. Just include the default config, and add a comment in the config on where to enable dx7 or dx8 wrapping.

### Version

x.x.x

**Comment by automata-rtx** [comment]
This is also quite helpful when needing to set an exception for another executable in the same directory as the game exe. For example, many Unreal Engine 2 games come with a level editor. With dxwrapper it's very easy to make sure the editor doesn't get translated to DX9 and therefore Remix won't initialize

**Comment by NV-LL** [comment]
Hi @Kim2091 - we already have REMIX-3034 open to investigate the possibility of this change. GH ticket #466 also requested the switch to dxwrapper, so we're going to close this as a duplicate. Please do upvote (👍) that other ticket if you haven't already, so that we can keep eye on how popular the request is. Also, if you want to add any info in a comment on that ticket, that'd be of great help! Thank you!
