### ISSUE TITLE
[Toolkit bug]: Overriding a texture slot that does not have a texture currently using the REST API does not work.

### ISSUE THREAD

**Issue by Frissj** [NVIDIAGameWorks/rtx-remix#669]
### Describe the bug

The same REST API command can either work on not depending if the material prim from /RootNode to Material was copied and pasted from the toolkit interface. Using a comparison checker, they look exactly the same comparing the one generated by my addon. 

You can use my addon to generate the REST API command if you want.

[SimpleRemix.zip](https://github.com/user-attachments/files/17586028/SimpleRemix.zip)

### How do you reproduce the bug?

https://github.com/user-attachments/assets/53d24b7d-d66b-4230-9de1-e38f9076efbb

### Version

2024.4.1

**Comment by po-trottier** [comment]
I believe you might be sending an incorrect request here since the feature worked fine when I tested and it's also the same endpoint we use for the [ComfyUI nodes](https://github.com/NVIDIAGameWorks/ComfyUI-RTX-Remix/blob/main/nodes/textures.py#L305).

Here are the steps you should follow to set a blank texture type:
1) Use the `Get Textures` endpoint to get the expected texture asset path (the shader input):
![image](https://github.com/user-attachments/assets/d795ddab-f7f7-402c-b034-9510c4eab27d)

2) Use the `Get Texture Material Input` endpoint with the path you got in the previous step to figure out the property path you want to set:
![image](https://github.com/user-attachments/assets/5582aace-4d6e-41b3-9979-44b26511bf3c)

3) Lastly, use the `Override Textures` endpoint with the new input path you got at the last step to set the texture in your mod:
![image](https://github.com/user-attachments/assets/4066cb58-d77e-4918-bf3e-b7dd151af1b0)

After that you should be able to execute `Get Textures` again and see your newly set texture:
![image](https://github.com/user-attachments/assets/3ae15ddb-216b-43ee-a9ee-43241b062a23)

You should also see the change reflected in the Toolkit:
![image](https://github.com/user-attachments/assets/7dc6a9c2-c384-43e8-bd05-64b187926ecd)
