### ISSUE TITLE
LNK1112 error.

### ISSUE THREAD

**Issue by sbartuk** [NVIDIAGameWorks/rtx-remix#83]
Getting this error "fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'" when running the command "powershell -command "& .\build_dxvk.ps1" Searched for hours for a solutionfor a way to change the target but cant find anything that works. Help :)

**Comment by nsubtil** [comment]
This usually means that you're trying to use the VS toolset for the wrong architecture (x86 vs x64).

We've since added some checks to the build files to detect and warn about this problem. Can you try again with the latest source? If you get the warnings, suggest checking that you're using the right VS command prompt variant, or just build from a regular command prompt (the build scripts should be able to find the right toolset automatically). Deleting the `_Comp*` directories may be necessary if that's the case.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
